version: "3.9"
services:
  web:
    build: backdoor-deals/
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./backdoor-deals/ 
        target: /app/
      - /app/node_modules
