import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Backroom Deals</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-gradient-to-tr from-purple-400  via-red-400  to-pink-400 container mx-auto min-h-screen min-w-full">
        <div className="container text-center justify-items-center ">
          <h1 className=" text-4xl font-bold ">
          <span className="text-6xl text-purple-800">B</span>ackroom
          <span className="text-6xl text-purple-800"> D</span>eals
          </h1>
          <div className="flex justify-center mx-auto min-h-1/2 min-w-1/3s">
            <Link
              href="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
              target="_blank"
              className="
                bg-red-200 rounded-3xl justify-center p-10 m-10 duration-0
                transition-all hover:ease-out hover:rounded-[50px]
                hover:translate-y-2
                hover:inset-2
                hover:text-white
                hover:bg-red-500 hover:shadow-lg
                hover:shadow-purple-600
                "
            >
              <h3 className=" underline font-semibold text-2xl"> Do Not Click Me!</h3>
              <div>
                Hmm, if you click me, you asked for it buddy.
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
