/* eslint-disable */
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import UserForm from "user/userForm";
import Layout from "../components/layout";


const Home: NextPage = () => {

  const [ isOpen, setOpen  ] = useState(false);

  const CheckIfUserVaild  = (user_time: string) => {
    if (!user_time){
      return false;
    }

    const original_time = new Date(user_time).getTime();
    const HOURS_TILL_EXP = 24;
    const current_time = new Date().getTime();
    const add_hours = (HOURS_TILL_EXP * 60) * 60 * 1000;
    const future_time = new Date(original_time + add_hours).getTime();
    
    if ( current_time < future_time ) {
      return true;
    }
    return false;
    
  }

  const handleClick = () => {
    const localData = localStorage.getItem('UserData');

    if( !!localData ) {
      const { regTime } =  JSON.parse(localData || '{}');
      if (CheckIfUserVaild(regTime)) {
        window.location.replace('/lobby/abc');
        return
      }
    }
    setOpen(!isOpen);
  }

  return (
    <>
      <Head>
        <title>Backroom Deals</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Layout>
        <div className="mx-auto min-h-screen min-w-1/2 self-center">
            <button
              onClick={() => handleClick()}
              className="
                bg-teal-200 rounded-3xl justify-center p-10 m-10 duration-0
                transition-all hover:ease-out hover:rounded-[50px]
                hover:translate-y-2
                hover:inset-2
                hover:text-white
                hover:bg-teal-500 hover:shadow-lg
                hover:shadow-teal-800
                "
            >
              <h3 className="font-semibold text-2xl"> Create Lobby  Tests !</h3>
            </button>
            {
             isOpen && 
              <div className="absolute inset-x-0 inset-y-50 ">
                <UserForm />
              </div>
            }
          </div>
      </Layout>
      </main>
    </>
  );
};

export default Home;
