version: "3.9"
services:
  web:
    build: . 
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true 
    volumes:
      - "./:/app/"
      - "/app/node_modules/"
